import type { HardNo, Item } from "./types";

// The full regimen as of Day 7 post-op (2026-04-23)
// Categorized per spec: permanent / temporary / cycled / situational / condition-linked

export const SEED_ITEMS: Item[] = [
  // ---------- PRE-BREAKFAST ----------
  {
    id: "seed-ds01",
    name: "Seed DS-01 Daily Synbiotic",
    brand: "Seed",
    dose: "2 caps",
    timing_slot: "pre_breakfast",
    schedule_rule: { frequency: "daily", notes: "Empty stomach, 30 min before food" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
    purchase_url: "https://seed.com/ds-01",
  },

  // ---------- BREAKFAST ----------
  {
    id: "vit-d3",
    name: "Vitamin D3 liquid",
    dose: "5000 IU",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    goals: ["foundational"],
    status: "active",
    notes: "Take with fat-containing meal",
  },
  {
    id: "umzu-daily-k",
    name: "UMZU Daily K (K2 MK-7)",
    brand: "UMZU",
    dose: "1 cap",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    goals: ["foundational"],
    status: "active",
    notes: "Bridge product — switching to Sports Research when empty",
    purchase_url: "https://umzu.com/products/daily-k",
  },
  {
    id: "umzu-tocotrienols",
    name: "UMZU Daily E (tocotrienols)",
    brand: "UMZU",
    dose: "50-100mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    goals: ["foundational"],
    status: "active",
    notes: "Low-dose, with fat. Post-op safe at this dose.",
    purchase_url: "https://umzu.com/products/daily-e",
  },
  {
    id: "umzu-sensolin",
    name: "UMZU Sensolin",
    brand: "UMZU",
    dose: "per label",
    timing_slot: "breakfast",
    schedule_rule: {
      frequency: "as_needed",
      notes: "15-20 min before any carb-containing meal",
    },
    category: "temporary",
    goals: ["metabolic", "seb_derm", "AGA"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "Reassess at Function Health bloodwork + Stelo CGM data",
    status: "active",
    notes: "Dihydroberberine. Blunts glucose spike = quieter DHT + quieter seb derm.",
    purchase_url: "https://umzu.com/products/sensolin",
  },
  {
    id: "hp-saw-palmetto",
    name: "Hairpower Saw Palmetto",
    brand: "Hairpower / Cosmedica",
    dose: "400mg (2 tabs)",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    goals: ["AGA", "hair"],
    status: "active",
    notes: "DHT modulation for transplant support",
  },
  {
    id: "hp-biotin",
    name: "Hairpower Biotin",
    brand: "Hairpower / Cosmedica",
    dose: "5mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    goals: ["hair"],
    status: "active",
    notes: "⚠️ PAUSE 72h BEFORE ANY BLOODWORK — biotin skews lab assays",
  },
  {
    id: "holy-basil-am",
    name: "Holy Basil Holixer (AM)",
    dose: "125mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "cycle_8_2", cycle_on_days: 56, cycle_off_days: 14 },
    category: "cycled",
    goals: ["cortisol"],
    status: "active",
    notes: "8 weeks on / 2 weeks off cycle",
  },
  {
    id: "pumpkin-seed-oil",
    name: "Pumpkin Seed Oil",
    dose: "400mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    goals: ["AGA", "hair"],
    status: "active",
    notes: "Softgel only (not whole seeds — trigger)",
  },
  {
    id: "mega-igg",
    name: "MegaIgG2000",
    brand: "Microbiome Labs",
    dose: "per label",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  },
  {
    id: "sunfiber",
    name: "Sunfiber PHGG",
    dose: "per label",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  },
  {
    id: "zinc-carnosine-am",
    name: "Zinc Carnosine (AM)",
    dose: "75mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
    notes: "Reduced from 150mg to 75mg AM + 75mg PM",
  },
  {
    id: "collagen",
    name: "Vital Proteins Collagen Peptides",
    brand: "Vital Proteins",
    dose: "20g (in coffee)",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    goals: ["skin_joints"],
    status: "active",
  },

  // ---------- PRE-WORKOUT / SITUATIONAL ----------
  {
    id: "l-citrulline",
    name: "L-Citrulline",
    dose: "6g",
    timing_slot: "pre_workout",
    schedule_rule: { frequency: "situational", notes: "Not daily — pre-workout only" },
    category: "situational",
    goals: ["circulation"],
    status: "active",
  },
  {
    id: "creatine",
    name: "Creatine Monohydrate",
    dose: "5g",
    timing_slot: "pre_workout",
    schedule_rule: { frequency: "daily", notes: "Timing doesn't matter — AM or pre-workout for convenience" },
    category: "permanent",
    goals: ["foundational"],
    status: "active",
  },
  {
    id: "l-glutamine-am",
    name: "L-Glutamine (AM)",
    dose: "5g",
    timing_slot: "pre_workout",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  },

  // ---------- DINNER ----------
  {
    id: "umzu-testrox",
    name: "UMZU Testro-X",
    brand: "UMZU",
    dose: "per label",
    timing_slot: "dinner",
    schedule_rule: { frequency: "cycle_8_2", cycle_on_days: 56, cycle_off_days: 14 },
    category: "cycled",
    goals: ["testosterone"],
    status: "active",
    notes: "PM dosing per your n=1 optimization. 8 on / 2 off.",
    purchase_url: "https://umzu.com/products/testro-x",
  },
  {
    id: "umzu-daily-mag",
    name: "UMZU Daily Magnesium",
    brand: "UMZU",
    dose: "420mg (4 caps)",
    timing_slot: "dinner",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    goals: ["sleep", "foundational"],
    status: "active",
    notes: "Bridge product — full 4-cap dose",
    purchase_url: "https://umzu.com/products/daily-magnesium",
  },
  {
    id: "holy-basil-pm",
    name: "Holy Basil Holixer (PM)",
    dose: "125mg",
    timing_slot: "dinner",
    schedule_rule: { frequency: "cycle_8_2", cycle_on_days: 56, cycle_off_days: 14 },
    category: "cycled",
    goals: ["cortisol"],
    status: "active",
  },
  {
    id: "zinc-carnosine-pm",
    name: "Zinc Carnosine (PM)",
    dose: "75mg",
    timing_slot: "dinner",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  },
  {
    id: "l-glutamine-pm",
    name: "L-Glutamine (PM)",
    dose: "5g",
    timing_slot: "dinner",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  },

  // ---------- PRE-BED ----------
  {
    id: "glycine",
    name: "Glycine",
    dose: "3g",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily", notes: "45 min before bed" },
    category: "permanent",
    goals: ["sleep"],
    status: "active",
  },
  {
    id: "l-theanine",
    name: "L-Theanine",
    dose: "200mg",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily", notes: "45 min before bed" },
    category: "permanent",
    goals: ["sleep"],
    status: "active",
  },
  {
    id: "tart-cherry",
    name: "Tart Cherry Juice",
    dose: "4 oz",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "cycled",
    goals: ["sleep"],
    status: "active",
    notes: "3x/week only — not daily",
  },
];

// Items queued for later activation (trigger-based)
export const QUEUED_ITEMS: Item[] = [
  {
    id: "q-omega3",
    name: "Nordic Naturals Ultimate Omega 2X",
    brand: "Nordic Naturals",
    dose: "2-3g EPA+DHA",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    goals: ["foundational", "inflammation"],
    review_trigger: "Day 14+ (antiplatelet window closes)",
    status: "queued",
    notes: "Currently Day 7 — wait for Day 14+ (Apr 30) to start full dose",
  },
  {
    id: "q-curcumin",
    name: "Thorne Meriva Curcumin",
    brand: "Thorne",
    dose: "500mg bid with fat",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["inflammation"],
    review_trigger: "Day 14+ (antiplatelet window closes)",
    status: "queued",
    notes: "6-12 mo duration",
  },
  {
    id: "q-procapil",
    name: "Hairpower Anti-Hair-Loss Serum (Procapil)",
    brand: "Hairpower / Cosmedica",
    dose: "nightly topical",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    goals: ["AGA", "hair"],
    review_trigger: "Day 21+",
    status: "queued",
  },
  {
    id: "q-keto-zpt",
    name: "Ketoconazole 2% Rx / Flakes ZPT alternating",
    dose: "shampoo, alternating",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 2 },
    category: "condition_linked",
    goals: ["seb_derm", "hair"],
    review_trigger: "Day 28+",
    status: "queued",
  },
  {
    id: "q-rosemary-azelaic",
    name: "Rosemary oil 1% in jojoba + Azelaic acid 15% 3x/wk",
    dose: "topical",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "condition_linked",
    goals: ["hair", "seb_derm"],
    review_trigger: "Day 30+",
    status: "queued",
  },
  {
    id: "q-redwood-max",
    name: "UMZU Redwood Max",
    brand: "UMZU",
    dose: "per label",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["circulation"],
    review_trigger: "Week 5 / Day 35+",
    status: "queued",
  },
  {
    id: "q-prp",
    name: "First PRP session (clinic)",
    dose: "1 session",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "condition_linked",
    goals: ["hair", "AGA"],
    review_trigger: "Month 3",
    status: "queued",
  },
  {
    id: "q-ghk-microneedle",
    name: "GHK-Cu copper peptide (NIOD CAIS 2) + Microneedling 0.6mm biweekly",
    dose: "topical + device",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 2 },
    category: "condition_linked",
    goals: ["hair", "AGA"],
    review_trigger: "Month 6+",
    status: "queued",
  },
  {
    id: "q-regenera",
    name: "Regenera Activa repeat (clinic)",
    dose: "1 session",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "condition_linked",
    goals: ["hair", "AGA"],
    review_trigger: "Month 12",
    status: "queued",
  },
];

// Back burner — parked with revisit conditions
export const BACKBURNER_ITEMS: Item[] = [
  {
    id: "bb-dutch",
    name: "DUTCH Complete hormone test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["testosterone"],
    review_trigger: "If Function Health shows unclear hormone picture",
    status: "backburner",
  },
  {
    id: "bb-gimap",
    name: "GI-MAP stool test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["gut", "seb_derm"],
    review_trigger: "If Month 3+ persistent gut/seb derm symptoms",
    status: "backburner",
  },
  {
    id: "bb-dao",
    name: "DAO serum test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["gut", "seb_derm"],
    review_trigger: "If histamine symptoms persist despite food elimination",
    status: "backburner",
  },
  {
    id: "bb-tongkat",
    name: "Tongkat Ali",
    dose: "TBD",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["testosterone"],
    review_trigger: "Post-bloodwork if free T below reference range",
    status: "backburner",
  },
  {
    id: "bb-boron",
    name: "Boron",
    dose: "10mg/day",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["testosterone"],
    review_trigger: "Post-bloodwork if T optimization needed",
    status: "backburner",
  },
  {
    id: "bb-pycnogenol",
    name: "Pycnogenol",
    dose: "100mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "situational",
    goals: ["circulation"],
    review_trigger: "Week 5+ if Redwood Max pine bark dose insufficient",
    status: "backburner",
  },
  {
    id: "bb-nad",
    name: "NAD+ precursors (NMN/NR)",
    dose: "TBD",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["longevity"],
    review_trigger: "Age 30+",
    status: "backburner",
  },
  {
    id: "bb-fisetin",
    name: "Fisetin senolytic",
    dose: "TBD",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "temporary",
    goals: ["longevity"],
    review_trigger: "Age 35+",
    status: "backburner",
  },
  {
    id: "bb-apigenin",
    name: "Apigenin pre-bed",
    dose: "50mg",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    goals: ["sleep", "longevity"],
    review_trigger: "Optional low-risk sleep add",
    status: "backburner",
  },
  {
    id: "bb-galleri",
    name: "Galleri cancer screen",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["longevity"],
    review_trigger: "Age 35+",
    status: "backburner",
  },
  {
    id: "bb-prenuvo",
    name: "Prenuvo full-body MRI",
    dose: "1 scan",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["longevity"],
    review_trigger: "Age 35+",
    status: "backburner",
  },
  {
    id: "bb-finasteride",
    name: "Finasteride/dutasteride",
    dose: "TBD",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    goals: ["AGA"],
    review_trigger: "ONLY IF AGA progresses despite stack (Year 2 reassessment) — currently HARD NO",
    status: "backburner",
  },
  {
    id: "bb-watchpat",
    name: "WatchPAT home sleep apnea test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["sleep"],
    review_trigger: "If snoring/daytime fatigue reported",
    status: "backburner",
  },
  {
    id: "bb-advanced-lipid",
    name: "Advanced lipid panel (ApoB, Lp(a))",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["foundational", "longevity"],
    review_trigger: "Add to Function Health if standard lipids concerning",
    status: "backburner",
  },
  {
    id: "bb-car",
    name: "Cortisol awakening response",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["cortisol"],
    review_trigger: "If HPA axis looks off on Function Health",
    status: "backburner",
  },
  {
    id: "bb-mb",
    name: "Methylene blue",
    dose: "TBD",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    goals: ["longevity"],
    review_trigger: "Insufficient evidence — revisit when data matures",
    status: "backburner",
  },
];

// HARD NO list — enforce in photo audits + Claude prompts
export const HARD_NOS: HardNo[] = [
  // Pharmaceuticals
  { category: "pharmaceutical", name: "Finasteride" },
  { category: "pharmaceutical", name: "Dutasteride" },
  { category: "pharmaceutical", name: "Minoxidil (oral or topical)" },

  // Foods
  { category: "food", name: "All dairy (including bovine colostrum)", reason: "Hits insulin + histamine + IGF-1 switches" },
  { category: "food", name: "Refined sugar" },
  { category: "food", name: "Honey", reason: "Mild seb derm flare" },
  { category: "food", name: "Dates", reason: "Strong seb derm flare trigger" },
  { category: "food", name: "Dried fruit", reason: "Sulfites + sugar spike" },
  { category: "food", name: "Dark chocolate", reason: "Mild seb derm flare" },
  { category: "food", name: "Seed oils (canola, soy, sunflower, corn, vegetable, cottonseed, safflower)" },
  { category: "food", name: "Alcohol" },
  { category: "food", name: "Aged / cured meats", reason: "Histamine" },
  { category: "food", name: "Bitter orange" },
  { category: "food", name: "Coconut water", reason: "Histamine" },
  { category: "food", name: "Walnuts" },
  { category: "food", name: "Almonds" },
  { category: "food", name: "Pumpkin seeds (whole)", reason: "Softgel OK, whole seeds trigger" },

  // Supplements
  { category: "supplement", name: "Ginkgo", reason: "Antiplatelet" },
  { category: "supplement", name: "Fo-Ti / He Shou Wu" },
  { category: "supplement", name: "Rapamycin", reason: "Immunosuppressive post-op" },
  { category: "supplement", name: "Metformin", reason: "Blunts exercise adaptations" },
  { category: "supplement", name: "Activated charcoal toothpaste" },

  // Specific products
  { category: "product", name: "UMZU zuPoo" },
  { category: "product", name: "UMZU Thyrite" },
  { category: "product", name: "UMZU Cortigon", reason: "Contains ginkgo" },
  { category: "product", name: "UMZU Choleast" },
  { category: "product", name: "UMZU zuACV" },
  { category: "product", name: "Hairpower Complex multivitamin", reason: "Contains ginkgo" },
  { category: "product", name: "Flakes Night Shift Serum" },
  { category: "product", name: "Blueprint products (all)" },

  // Tests
  { category: "test", name: "IgG food sensitivity panels", reason: "Not clinically valid" },

  // Approaches
  { category: "approach", name: "Plasma exchange" },
  { category: "approach", name: "Gene therapy" },
];
