import type { HardNo, Item } from "./types";

// Helper to reduce boilerplate — every seed item gets seed_id === id
function seed(item: Omit<Item, "seed_id"> & { seed_id?: string }): Item {
  return { ...item, seed_id: item.seed_id ?? item.id };
}

// =========================================================
// ACTIVE ITEMS — Day 7+ post-op regimen
// =========================================================
export const SEED_ITEMS: Item[] = [
  // ---------------- SUPPLEMENTS: Pre-breakfast ----------------
  seed({
    id: "seed-ds01",
    name: "Seed DS-01 Daily Synbiotic",
    brand: "Seed",
    dose: "2 caps",
    timing_slot: "pre_breakfast",
    schedule_rule: { frequency: "daily", notes: "Empty stomach, 30 min before food" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
    purchase_url: "https://seed.com/ds-01",
  }),

  // ---------------- SUPPLEMENTS: Breakfast ----------------
  seed({
    id: "vit-d3",
    name: "Vitamin D3 liquid",
    dose: "5000 IU",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "supplement",
    goals: ["foundational"],
    status: "active",
    notes: "Take with fat-containing meal",
  }),
  seed({
    id: "umzu-daily-k",
    name: "UMZU Daily K (K2 MK-7)",
    brand: "UMZU",
    dose: "1 cap",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "supplement",
    goals: ["foundational"],
    status: "active",
    notes: "Bridge product — switching to Sports Research when empty",
    purchase_url: "https://umzu.com/products/daily-k",
  }),
  seed({
    id: "umzu-tocotrienols",
    name: "UMZU Daily E (tocotrienols)",
    brand: "UMZU",
    dose: "50-100mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "supplement",
    goals: ["foundational"],
    status: "active",
    notes: "Low-dose, with fat. Post-op safe at this dose.",
    purchase_url: "https://umzu.com/products/daily-e",
  }),
  seed({
    id: "umzu-sensolin",
    name: "UMZU Sensolin",
    brand: "UMZU",
    dose: "per label",
    timing_slot: "breakfast",
    schedule_rule: {
      frequency: "as_needed",
      notes: "15-20 min before any carb-containing meal",
    },
    category: "temporary",
    item_type: "supplement",
    goals: ["metabolic", "seb_derm", "AGA"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "Reassess at Function Health bloodwork + Stelo CGM data",
    status: "active",
    notes: "Dihydroberberine. Blunts glucose spike = quieter DHT + quieter seb derm.",
    purchase_url: "https://umzu.com/products/sensolin",
  }),
  seed({
    id: "hp-saw-palmetto",
    name: "Hairpower Saw Palmetto",
    brand: "Hairpower / Cosmedica",
    dose: "400mg (2 tabs)",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "supplement",
    goals: ["AGA", "hair"],
    status: "active",
    notes: "DHT modulation for transplant support",
  }),
  seed({
    id: "hp-biotin",
    name: "Hairpower Biotin",
    brand: "Hairpower / Cosmedica",
    dose: "5mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "supplement",
    goals: ["hair"],
    status: "active",
    notes: "⚠️ PAUSE 72h BEFORE ANY BLOODWORK — biotin skews lab assays",
  }),
  seed({
    id: "holy-basil-am",
    name: "Holy Basil Holixer (AM)",
    dose: "125mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "cycle_8_2", cycle_on_days: 56, cycle_off_days: 14 },
    category: "cycled",
    item_type: "supplement",
    goals: ["cortisol"],
    status: "active",
    notes: "8 weeks on / 2 weeks off cycle",
  }),
  seed({
    id: "pumpkin-seed-oil",
    name: "Pumpkin Seed Oil",
    dose: "400mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "supplement",
    goals: ["AGA", "hair"],
    status: "active",
    notes: "Softgel only (not whole seeds — trigger)",
  }),
  seed({
    id: "mega-igg",
    name: "MegaIgG2000",
    brand: "Microbiome Labs",
    dose: "per label",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  }),
  seed({
    id: "sunfiber",
    name: "Sunfiber PHGG",
    dose: "per label",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  }),
  seed({
    id: "zinc-carnosine-am",
    name: "Zinc Carnosine (AM)",
    dose: "75mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
    notes: "Reduced from 150mg to 75mg AM + 75mg PM",
  }),
  seed({
    id: "collagen",
    name: "Vital Proteins Collagen Peptides",
    brand: "Vital Proteins",
    dose: "20g (in coffee)",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "supplement",
    goals: ["skin_joints"],
    status: "active",
  }),

  // ---------------- SUPPLEMENTS: Pre-workout / situational ----------------
  seed({
    id: "l-citrulline",
    name: "L-Citrulline",
    dose: "6g",
    timing_slot: "pre_workout",
    schedule_rule: { frequency: "situational", notes: "Not daily — pre-workout only" },
    category: "situational",
    item_type: "supplement",
    goals: ["circulation"],
    status: "active",
  }),
  seed({
    id: "creatine",
    name: "Creatine Monohydrate",
    dose: "5g",
    timing_slot: "pre_workout",
    schedule_rule: { frequency: "daily", notes: "Timing doesn't matter — AM or pre-workout for convenience" },
    category: "permanent",
    item_type: "supplement",
    goals: ["foundational"],
    status: "active",
  }),
  seed({
    id: "l-glutamine-am",
    name: "L-Glutamine (AM)",
    dose: "5g",
    timing_slot: "pre_workout",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  }),

  // ---------------- SUPPLEMENTS: Dinner ----------------
  seed({
    id: "umzu-testrox",
    name: "UMZU Testro-X",
    brand: "UMZU",
    dose: "per label",
    timing_slot: "dinner",
    schedule_rule: { frequency: "cycle_8_2", cycle_on_days: 56, cycle_off_days: 14 },
    category: "cycled",
    item_type: "supplement",
    goals: ["testosterone"],
    status: "active",
    notes: "PM dosing per your n=1 optimization. 8 on / 2 off.",
    purchase_url: "https://umzu.com/products/testro-x",
  }),
  seed({
    id: "umzu-daily-mag",
    name: "UMZU Daily Magnesium",
    brand: "UMZU",
    dose: "420mg (4 caps)",
    timing_slot: "dinner",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "supplement",
    goals: ["sleep", "foundational"],
    status: "active",
    notes: "Bridge product — full 4-cap dose",
    purchase_url: "https://umzu.com/products/daily-magnesium",
  }),
  seed({
    id: "holy-basil-pm",
    name: "Holy Basil Holixer (PM)",
    dose: "125mg",
    timing_slot: "dinner",
    schedule_rule: { frequency: "cycle_8_2", cycle_on_days: 56, cycle_off_days: 14 },
    category: "cycled",
    item_type: "supplement",
    goals: ["cortisol"],
    status: "active",
  }),
  seed({
    id: "zinc-carnosine-pm",
    name: "Zinc Carnosine (PM)",
    dose: "75mg",
    timing_slot: "dinner",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  }),
  seed({
    id: "l-glutamine-pm",
    name: "L-Glutamine (PM)",
    dose: "5g",
    timing_slot: "dinner",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["gut"],
    started_on: "2026-04-23",
    ends_on: "2026-10-23",
    review_trigger: "6-month gut protocol review",
    status: "active",
  }),

  // ---------------- SUPPLEMENTS: Pre-bed ----------------
  seed({
    id: "glycine",
    name: "Glycine",
    dose: "3g",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily", notes: "45 min before bed" },
    category: "permanent",
    item_type: "supplement",
    goals: ["sleep"],
    status: "active",
  }),
  seed({
    id: "l-theanine",
    name: "L-Theanine",
    dose: "200mg",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily", notes: "45 min before bed" },
    category: "permanent",
    item_type: "supplement",
    goals: ["sleep"],
    status: "active",
  }),
  seed({
    id: "tart-cherry",
    name: "Tart Cherry Juice",
    dose: "4 oz",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "cycled",
    item_type: "supplement",
    goals: ["sleep"],
    status: "active",
    notes: "3x/week only — not daily",
  }),

  // ---------------- TOPICALS (active now) ----------------
  seed({
    id: "cosmedica-shampoo",
    name: "Cosmedica post-op shampoo",
    brand: "Cosmedica / Hairpower",
    dose: "gentle wash",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily", notes: "AM or PM — foam, pat, 5-10 min soak, rinse low-pressure" },
    category: "condition_linked",
    item_type: "topical",
    goals: ["hair", "recovery"],
    status: "active",
    notes: "Day 1-14 gentle wash protocol per clinic",
  }),
  seed({
    id: "saline-mist",
    name: "Sterile saline mist",
    dose: "every 2-3h",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily", notes: "Every 2-3h while crusts present" },
    category: "condition_linked",
    item_type: "topical",
    goals: ["recovery", "hair"],
    status: "active",
    notes: "DIY or NeilMed/Simply Saline. Keep grafts moist, loosen crusts.",
  }),
  seed({
    id: "hocl-spray",
    name: "BLDG Active Skin Repair (HOCl)",
    brand: "BLDG Active",
    dose: "spot application",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed", notes: "Donor area if irritated. Not over grafts heavy." },
    category: "condition_linked",
    item_type: "topical",
    goals: ["recovery"],
    status: "active",
    purchase_url: "https://activeskinrepair.com",
  }),

  // ---------------- DEVICES (active) ----------------
  seed({
    id: "oura-ring",
    name: "Oura Ring 4",
    brand: "Oura",
    dose: "24/7 wear",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "ongoing" },
    category: "permanent",
    item_type: "device",
    goals: ["sleep", "foundational"],
    status: "active",
    notes: "HRV, RHR, deep/REM, temp deviation. Data pulls in via /data import.",
    purchase_url: "https://ouraring.com",
  }),
  seed({
    id: "stelo-cgm",
    name: "Dexcom Stelo CGM",
    brand: "Dexcom",
    dose: "continuous wear (15-day sensors)",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "ongoing" },
    category: "temporary",
    item_type: "device",
    goals: ["metabolic", "seb_derm"],
    status: "active",
    notes: "Monitor glucose spikes to confirm trigger foods",
    purchase_url: "https://stelo.com",
  }),
  seed({
    id: "mouth-tape",
    name: "Mouth tape",
    brand: "3M Micropore or Hostage Tape",
    dose: "nightly",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "device",
    goals: ["sleep"],
    status: "active",
  }),

  // ---------------- PRACTICES (active now) ----------------
  seed({
    id: "sleep-elevated",
    name: "Sleep elevated 30-45° with towel doughnut",
    dose: "nightly",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily", notes: "Day 1-14 post-op to protect crown + donor" },
    category: "condition_linked",
    item_type: "practice",
    goals: ["recovery", "hair"],
    started_on: "2026-04-17",
    ends_on: "2026-05-01",
    status: "active",
  }),
  seed({
    id: "bedroom-cool",
    name: "Bedroom at 65-68°F",
    dose: "nightly",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "practice",
    goals: ["sleep"],
    status: "active",
  }),
  seed({
    id: "morning-sun",
    name: "Morning sunlight 10 min",
    dose: "10 min",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily", notes: "Outdoors, no sunglasses, within 1h of waking" },
    category: "permanent",
    item_type: "practice",
    goals: ["sleep", "cortisol"],
    status: "active",
  }),
  seed({
    id: "no-screens-pre-bed",
    name: "No screens 1h pre-bed",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "practice",
    goals: ["sleep"],
    status: "active",
  }),
  seed({
    id: "mobility",
    name: "Mobility / stretching",
    dose: "10-15 min",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "practice",
    goals: ["foundational"],
    status: "active",
  }),
  seed({
    id: "zone2-cardio",
    name: "Zone 2 cardio",
    dose: "30-45 min",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "permanent",
    item_type: "practice",
    goals: ["foundational"],
    status: "active",
    notes: "Light walk / easy bike — gentle Day 7-14",
  }),

  // ---------------- FOOD (staples) ----------------
  seed({
    id: "bone-broth",
    name: "Bone broth",
    dose: "8-12 oz",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["gut", "recovery"],
    status: "active",
  }),
  seed({
    id: "lifeboost-coffee",
    name: "Lifeboost coffee",
    brand: "Lifeboost",
    dose: "1-2 cups",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily", notes: "After food, not first thing — cortisol timing" },
    category: "permanent",
    item_type: "food",
    goals: ["foundational"],
    status: "active",
    purchase_url: "https://lifeboostcoffee.com",
  }),
  seed({
    id: "grassfed-beef",
    name: "Grass-fed ground beef",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["foundational"],
    status: "active",
  }),
  seed({
    id: "wild-salmon",
    name: "Wild salmon / seabass",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "permanent",
    item_type: "food",
    goals: ["foundational", "inflammation"],
    status: "active",
  }),
  seed({
    id: "pasture-eggs",
    name: "Pasture-raised eggs",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["foundational"],
    status: "active",
  }),
  seed({
    id: "blueberries",
    name: "Organic blueberries",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["foundational"],
    status: "active",
  }),
  seed({
    id: "kimchi",
    name: "Kimchi (unpasteurized)",
    dose: "2-3 forkfuls",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["gut"],
    status: "active",
  }),

  // ---------------- GEAR ----------------
  seed({
    id: "silk-pillowcase",
    name: "Silk pillowcase",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "ongoing" },
    category: "condition_linked",
    item_type: "gear",
    goals: ["hair", "skin_joints"],
    status: "active",
    notes: "Less friction on hair + skin during sleep",
  }),
  seed({
    id: "sleep-mask",
    name: "Blackout sleep mask",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "gear",
    goals: ["sleep"],
    status: "active",
  }),
  seed({
    id: "towel-doughnut",
    name: "Towel doughnut (crown protection)",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "gear",
    goals: ["recovery", "hair"],
    started_on: "2026-04-17",
    ends_on: "2026-05-01",
    status: "active",
    notes: "Day 1-14 — roll towel into ring, cradle neck, keeps crown off pillow",
  }),
];

// =========================================================
// QUEUED — trigger-based future additions
// =========================================================
export const QUEUED_ITEMS: Item[] = [
  // Supplements
  seed({
    id: "q-omega3",
    name: "Nordic Naturals Ultimate Omega 2X",
    brand: "Nordic Naturals",
    dose: "2-3g EPA+DHA",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "supplement",
    goals: ["foundational", "inflammation"],
    review_trigger: "Day 14+ (antiplatelet window closes)",
    status: "queued",
    notes: "Currently Day 7 — wait for Day 14+ (Apr 30) to start full dose",
  }),
  seed({
    id: "q-curcumin",
    name: "Thorne Meriva Curcumin",
    brand: "Thorne",
    dose: "500mg bid with fat",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["inflammation"],
    review_trigger: "Day 14+ (antiplatelet window closes)",
    status: "queued",
    notes: "6-12 mo duration",
  }),

  // Topicals queued
  seed({
    id: "q-procapil",
    name: "Hairpower Anti-Hair-Loss Serum (Procapil)",
    brand: "Hairpower / Cosmedica",
    dose: "nightly topical",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "topical",
    goals: ["AGA", "hair"],
    review_trigger: "Day 21+",
    status: "queued",
  }),
  seed({
    id: "q-keto",
    name: "Ketoconazole 2% Rx shampoo",
    dose: "2×/week alternating",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 2 },
    category: "condition_linked",
    item_type: "topical",
    goals: ["seb_derm", "hair"],
    review_trigger: "Day 28+ (telehealth Rx via Strut/Happy Head)",
    status: "queued",
  }),
  seed({
    id: "q-zpt",
    name: "Flakes ZPT 2% shampoo",
    brand: "Flakes",
    dose: "2×/week alternating with ketoconazole",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 2 },
    category: "condition_linked",
    item_type: "topical",
    goals: ["seb_derm"],
    review_trigger: "Day 28+",
    status: "queued",
  }),
  seed({
    id: "q-rosemary-oil",
    name: "Rosemary oil 1% in jojoba",
    dose: "scalp topical, few drops",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "condition_linked",
    item_type: "topical",
    goals: ["hair"],
    review_trigger: "Day 30+",
    status: "queued",
  }),
  seed({
    id: "q-azelaic",
    name: "Azelaic acid 15% on scalp",
    dose: "3x/wk",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "condition_linked",
    item_type: "topical",
    goals: ["seb_derm", "hair"],
    review_trigger: "Day 30+ with surgeon clearance",
    status: "queued",
  }),
  seed({
    id: "q-ghk-cu",
    name: "GHK-Cu copper peptide (NIOD CAIS 2)",
    brand: "NIOD",
    dose: "topical",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "condition_linked",
    item_type: "topical",
    goals: ["hair", "skin_joints"],
    review_trigger: "Month 6+",
    status: "queued",
  }),
  seed({
    id: "q-spf-scalp",
    name: "EltaMD UV Clear SPF 46 on scalp",
    brand: "EltaMD",
    dose: "when outdoors without hat",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "condition_linked",
    item_type: "topical",
    goals: ["hair", "recovery"],
    review_trigger: "Day 14+",
    status: "queued",
  }),

  // Face skincare queued for Day 14+
  seed({
    id: "q-vitc-serum",
    name: "Vitamin C serum (SkinCeuticals CE Ferulic or Maelove Glow Maker)",
    dose: "AM, face only",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "topical",
    goals: ["skin_joints"],
    review_trigger: "Day 14+",
    status: "queued",
  }),
  seed({
    id: "q-retinoid",
    name: "Medik8 Crystal Retinal 3 (face only)",
    brand: "Medik8",
    dose: "PM, face only",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "condition_linked",
    item_type: "topical",
    goals: ["skin_joints"],
    review_trigger: "Day 14+",
    status: "queued",
  }),

  // Devices queued
  seed({
    id: "q-irestore",
    name: "iRestore Elite LLLT helmet",
    brand: "iRestore",
    dose: "20 min, 3-4x/wk",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 4 },
    category: "condition_linked",
    item_type: "device",
    goals: ["hair", "AGA"],
    review_trigger: "Week 4-6+ (scalp fully healed)",
    status: "queued",
    purchase_url: "https://irestorelaser.com",
  }),
  seed({
    id: "q-red-light",
    name: "Red light face/body panel (Mito Red or Bon Charge)",
    dose: "10-20 min",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 4 },
    category: "permanent",
    item_type: "device",
    goals: ["skin_joints", "recovery"],
    review_trigger: "Day 14+ (face + body only, NOT scalp — iRestore serves that)",
    status: "queued",
  }),
  seed({
    id: "q-microneedle",
    name: "Dermaroller 0.5-0.75mm (at home)",
    dose: "biweekly",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 1 },
    category: "condition_linked",
    item_type: "device",
    goals: ["hair", "AGA"],
    review_trigger: "Month 4-6+",
    status: "queued",
  }),
  seed({
    id: "q-cooling-mattress",
    name: "Eight Sleep Pod 4 or ChiliPad Dock Pro",
    dose: "nightly",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "device",
    goals: ["sleep"],
    review_trigger: "When budget/priority aligns",
    status: "queued",
  }),

  // Procedures queued
  seed({
    id: "q-prp-1",
    name: "PRP session 1 (clinic)",
    dose: "1 session",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "condition_linked",
    item_type: "procedure",
    goals: ["hair", "AGA"],
    review_trigger: "Month 3",
    status: "queued",
  }),
  seed({
    id: "q-regenera",
    name: "Regenera Activa repeat (clinic)",
    dose: "1 session",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "condition_linked",
    item_type: "procedure",
    goals: ["hair", "AGA"],
    review_trigger: "Month 12",
    status: "queued",
  }),

  // Practices queued
  seed({
    id: "q-scalp-massage",
    name: "Koyama standardized scalp massage",
    dose: "4 min, 2x/day",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily", notes: "2x/day, 4 min each, pinch-&-twirl" },
    category: "condition_linked",
    item_type: "practice",
    goals: ["hair", "AGA"],
    review_trigger: "Day 14+ (grafts locked in)",
    status: "queued",
  }),
  seed({
    id: "q-sauna",
    name: "Sauna",
    dose: "20 min, 3x/wk",
    timing_slot: "situational",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "permanent",
    item_type: "practice",
    goals: ["recovery", "longevity"],
    review_trigger: "Day 30+ (scalp healed)",
    status: "queued",
  }),
  seed({
    id: "q-cold-shower",
    name: "Cold shower / cold plunge",
    dose: "2-3 min",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "practice",
    goals: ["recovery", "cortisol"],
    review_trigger: "Day 14+ (avoid scalp direct cold first 2 weeks)",
    status: "queued",
  }),
  seed({
    id: "q-resistance-training",
    name: "Resistance training",
    dose: "3x/wk",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "weekly", days_per_week: 3 },
    category: "permanent",
    item_type: "practice",
    goals: ["foundational", "testosterone"],
    review_trigger: "Day 21+ (resume upper/lower split)",
    status: "queued",
  }),
  seed({
    id: "q-hiit",
    name: "VO2max / HIIT intervals",
    dose: "1-2x/wk",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "weekly", days_per_week: 2 },
    category: "permanent",
    item_type: "practice",
    goals: ["foundational", "longevity"],
    review_trigger: "Week 5 / Day 35+",
    status: "queued",
  }),
  seed({
    id: "q-tre",
    name: "Time-restricted eating (14:10 → 16:8)",
    dose: "daily window",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "practice",
    goals: ["metabolic", "longevity"],
    review_trigger: "Month 3+",
    status: "queued",
  }),

  // Food queued
  seed({
    id: "q-kasandrinos",
    name: "Kasandrinos EVOO",
    brand: "Kasandrinos",
    dose: "2 tbsp/day",
    timing_slot: "ongoing",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["inflammation", "longevity"],
    review_trigger: "Day 14+ (swap in when post-op)",
    status: "queued",
    purchase_url: "https://kasandrinos.com",
  }),
  seed({
    id: "q-broccoli-sprouts",
    name: "Broccoli sprouts (home-grown or Avmacol ES)",
    dose: "30-50g raw or 3 caps",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "permanent",
    item_type: "food",
    goals: ["longevity", "seb_derm"],
    review_trigger: "Day 14+",
    status: "queued",
    notes: "Sulforaphane / NRF2 pathway",
  }),

  // Redwood Max — situational circulation support
  seed({
    id: "q-redwood-max",
    name: "UMZU Redwood Max",
    brand: "UMZU",
    dose: "per label",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "supplement",
    goals: ["circulation"],
    review_trigger: "Week 5 / Day 35+",
    status: "queued",
  }),

  // Tests queued
  seed({
    id: "q-function-health",
    name: "Function Health annual panel",
    brand: "Function Health",
    dose: "~100 biomarkers",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "permanent",
    item_type: "test",
    goals: ["foundational"],
    review_trigger: "Week 8-10 / Jun 18 · PAUSE BIOTIN Jun 15",
    status: "queued",
    purchase_url: "https://functionhealth.com",
  }),
  seed({
    id: "q-trudiag",
    name: "TruDiagnostic TruAge Complete",
    brand: "TruDiagnostic",
    dose: "epigenetic age + pace",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "permanent",
    item_type: "test",
    goals: ["longevity"],
    review_trigger: "Month 3 baseline, then every 6 mo",
    status: "queued",
    purchase_url: "https://trudiagnostic.com",
  }),
];

// =========================================================
// BACK BURNER — parked with revisit conditions
// =========================================================
export const BACKBURNER_ITEMS: Item[] = [
  seed({
    id: "bb-dutch",
    name: "DUTCH Complete hormone test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["testosterone"],
    review_trigger: "If Function Health shows unclear hormone picture",
    status: "backburner",
  }),
  seed({
    id: "bb-gimap",
    name: "GI-MAP stool test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["gut", "seb_derm"],
    review_trigger: "If Month 3+ persistent gut/seb derm symptoms",
    status: "backburner",
  }),
  seed({
    id: "bb-dao",
    name: "DAO serum test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["gut", "seb_derm"],
    review_trigger: "If histamine symptoms persist despite food elimination",
    status: "backburner",
  }),
  seed({
    id: "bb-tongkat",
    name: "Tongkat Ali",
    dose: "TBD",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["testosterone"],
    review_trigger: "Post-bloodwork if free T below reference range",
    status: "backburner",
  }),
  seed({
    id: "bb-boron",
    name: "Boron",
    dose: "10mg/day",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["testosterone"],
    review_trigger: "Post-bloodwork if T optimization needed",
    status: "backburner",
  }),
  seed({
    id: "bb-pycnogenol",
    name: "Pycnogenol",
    dose: "100mg",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "situational",
    item_type: "supplement",
    goals: ["circulation"],
    review_trigger: "Week 5+ if Redwood Max pine bark dose insufficient",
    status: "backburner",
  }),
  seed({
    id: "bb-nad",
    name: "NAD+ precursors (NMN/NR)",
    dose: "TBD",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["longevity"],
    review_trigger: "Age 30+",
    status: "backburner",
  }),
  seed({
    id: "bb-fisetin",
    name: "Fisetin senolytic",
    dose: "TBD",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "temporary",
    item_type: "supplement",
    goals: ["longevity"],
    review_trigger: "Age 35+",
    status: "backburner",
  }),
  seed({
    id: "bb-apigenin",
    name: "Apigenin pre-bed",
    dose: "50mg",
    timing_slot: "pre_bed",
    schedule_rule: { frequency: "daily" },
    category: "temporary",
    item_type: "supplement",
    goals: ["sleep", "longevity"],
    review_trigger: "Optional low-risk sleep add",
    status: "backburner",
  }),
  seed({
    id: "bb-galleri",
    name: "Galleri cancer screen",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["longevity"],
    review_trigger: "Age 35+",
    status: "backburner",
  }),
  seed({
    id: "bb-prenuvo",
    name: "Prenuvo full-body MRI",
    dose: "1 scan",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["longevity"],
    review_trigger: "Age 35+",
    status: "backburner",
  }),
  seed({
    id: "bb-finasteride",
    name: "Finasteride/dutasteride",
    dose: "TBD",
    timing_slot: "breakfast",
    schedule_rule: { frequency: "daily" },
    category: "condition_linked",
    item_type: "supplement",
    goals: ["AGA"],
    review_trigger: "ONLY if AGA progresses despite stack (Year 2 reassessment) — currently HARD NO",
    status: "backburner",
  }),
  seed({
    id: "bb-watchpat",
    name: "WatchPAT home sleep apnea test",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["sleep"],
    review_trigger: "If snoring/daytime fatigue reported",
    status: "backburner",
  }),
  seed({
    id: "bb-advanced-lipid",
    name: "Advanced lipid panel (ApoB, Lp(a))",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["foundational", "longevity"],
    review_trigger: "Add to Function Health if standard lipids concerning",
    status: "backburner",
  }),
  seed({
    id: "bb-car",
    name: "Cortisol awakening response",
    dose: "1 test",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "test",
    goals: ["cortisol"],
    review_trigger: "If HPA axis looks off on Function Health",
    status: "backburner",
  }),
  seed({
    id: "bb-mb",
    name: "Methylene blue",
    dose: "TBD",
    timing_slot: "situational",
    schedule_rule: { frequency: "as_needed" },
    category: "situational",
    item_type: "supplement",
    goals: ["longevity"],
    review_trigger: "Insufficient evidence — revisit when data matures",
    status: "backburner",
  }),
];

// =========================================================
// HARD NO list
// =========================================================
export const HARD_NOS: HardNo[] = [
  // Pharmaceuticals
  { category: "pharmaceutical", name: "Finasteride" },
  { category: "pharmaceutical", name: "Dutasteride" },
  { category: "pharmaceutical", name: "Minoxidil (oral or topical)" },

  // Foods
  { category: "food", name: "All dairy (including bovine colostrum)", reason: "Hits insulin + histamine + IGF-1 switches" },
  { category: "food", name: "Refined sugar" },
  { category: "food", name: "Honey", reason: "Mild seb derm flare" },
  { category: "food", name: "Dates", reason: "Strong seb derm flare trigger" },
  { category: "food", name: "Dried fruit", reason: "Sulfites + sugar spike" },
  { category: "food", name: "Dark chocolate", reason: "Mild seb derm flare" },
  { category: "food", name: "Seed oils (canola, soy, sunflower, corn, vegetable, cottonseed, safflower)" },
  { category: "food", name: "Alcohol" },
  { category: "food", name: "Aged / cured meats", reason: "Histamine" },
  { category: "food", name: "Bitter orange" },
  { category: "food", name: "Coconut water", reason: "Histamine" },
  { category: "food", name: "Walnuts" },
  { category: "food", name: "Almonds" },
  { category: "food", name: "Pumpkin seeds (whole)", reason: "Softgel OK, whole seeds trigger" },

  // Supplements
  { category: "supplement", name: "Ginkgo", reason: "Antiplatelet" },
  { category: "supplement", name: "Fo-Ti / He Shou Wu" },
  { category: "supplement", name: "Rapamycin", reason: "Immunosuppressive post-op" },
  { category: "supplement", name: "Metformin", reason: "Blunts exercise adaptations" },
  { category: "supplement", name: "Activated charcoal toothpaste" },

  // Specific products
  { category: "product", name: "UMZU zuPoo" },
  { category: "product", name: "UMZU Thyrite" },
  { category: "product", name: "UMZU Cortigon", reason: "Contains ginkgo" },
  { category: "product", name: "UMZU Choleast" },
  { category: "product", name: "UMZU zuACV" },
  { category: "product", name: "Hairpower Complex multivitamin", reason: "Contains ginkgo" },
  { category: "product", name: "Flakes Night Shift Serum" },
  { category: "product", name: "Blueprint products (all)" },

  // Tests
  { category: "test", name: "IgG food sensitivity panels", reason: "Not clinically valid" },

  // Approaches
  { category: "approach", name: "Plasma exchange" },
  { category: "approach", name: "Gene therapy" },
];
