// /terms — terms of use. Required for App Store + sane liability
// posture for a health-adjacent app. Plain-English. Not legal advice
// — for final wording before public launch, run this past a lawyer.

import Link from "next/link";
import PageHeader from "@/components/ui/PageHeader";
import { createClient } from "@/lib/supabase/server";

export const metadata = {
  title: "Terms — Regimen",
};

export default async function TermsPage() {
  // Public page: signed-in readers go back to You, signed-out readers
  // (from the landing or sign-in screen) go back home.
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <div className="pb-24">
      <PageHeader
        title="Terms of use"
        subtitle="Last updated: May 8, 2026."
        back={user ? "/you" : "/"}
        backLabel={user ? "You" : "Home"}
        showCoach={false}
      />

      <article className="max-w-[65ch] space-y-9 text-body text-[var(--foreground-soft)]">
        <Section title="1. Not medical advice">
          <p>
            Regimen is an organizational tool for tracking supplements,
            food, training, and personal health data. Coach&apos;s output
            is generated by a large language model (Anthropic Claude)
            trained on public information; it is not personalized medical
            advice and is not a substitute for evaluation by a licensed
            clinician.
          </p>
          <p>
            <strong className="font-semibold text-[var(--foreground)]">
              Do not start, stop, or change any prescription medication,
              supplement protocol, or treatment based on anything this app
              tells you. Talk to your physician first.
            </strong>{" "}
            If you experience any concerning symptom, stop using the app and
            seek medical care.
          </p>
          <p>
            Regimen does not diagnose, treat, cure, or prevent any disease.
            We make no health outcome guarantees.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be 18 or older to use Regimen. By using the app you
            represent that you are 18+ and legally able to enter this
            agreement.
          </p>
        </Section>

        <Section title="3. Your account">
          <p>
            You&apos;re responsible for your account credentials and all
            activity under your account. Don&apos;t share your sign-in
            link. Notify us at security@regimen.app if you suspect
            unauthorized access.
          </p>
          <p>
            We may suspend or terminate accounts that we reasonably
            believe are abusing the service (scripted overuse, attempts to
            poison shared catalog data, etc.).
          </p>
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc space-y-2.5 pl-5 marker:text-[var(--muted)]">
            <li>Use the app for anyone other than yourself.</li>
            <li>
              Submit false or misleading entries to the shared product
              catalog (poisoning the catalog harms every other user).
            </li>
            <li>
              Try to extract Coach prompts, jailbreak the model, or use the
              service to generate content that violates Anthropic&apos;s
              usage policies.
            </li>
            <li>
              Reverse-engineer the app, scrape it, or send automated
              traffic to our servers.
            </li>
            <li>
              Upload anyone else&apos;s personal health information without
              their explicit consent.
            </li>
          </ul>
        </Section>

        <Section title="5. Affiliate links">
          <p>
            Some product links in the app are affiliate links. If you click
            through and make a purchase, we may earn a small commission at
            no extra cost to you. Affiliate relationships do not influence
            which items Coach recommends — recommendations are based only
            on your stated goals, hard NOs, and stack interactions.
          </p>
        </Section>

        <Section title="6. Subscriptions (when available)">
          <p>
            Pro tier subscriptions, when offered, are billed through Stripe
            and auto-renew at the stated interval until cancelled. You can
            cancel anytime from <Link href="/account" className="text-[var(--foreground)] underline underline-offset-2">Account</Link>;
            cancellation takes effect at the end of the current billing
            period. No prorated refunds for partial periods unless required
            by law.
          </p>
        </Section>

        <Section title="7. Disclaimers and limitation of liability">
          <p>
            The app is provided &ldquo;as is.&rdquo; To the maximum extent
            permitted by law, we disclaim all warranties including
            merchantability, fitness for a particular purpose, and
            non-infringement. We do not warrant that the app is free from
            errors, that Coach&apos;s output is accurate, or that the
            service is uninterrupted.
          </p>
          <p>
            <strong className="font-semibold text-[var(--foreground)]">
              We are not liable for indirect, incidental, special, or
              consequential damages — including any health outcome — arising
              from your use of the app. Our total liability for any claim
              is limited to the amount you paid us in the 12 months before
              the claim arose, or $50, whichever is greater.
            </strong>
          </p>
        </Section>

        <Section title="8. Privacy">
          <p>
            How we handle your data is described in the{" "}
            <Link href="/privacy" className="text-[var(--foreground)] underline underline-offset-2">
              Privacy policy
            </Link>
            . By using the app you accept that policy.
          </p>
        </Section>

        <Section title="9. Changes">
          <p>
            We may update these terms. Material changes will be announced
            in-app and the &ldquo;Last updated&rdquo; date will change.
            Continuing to use the app after a change means you accept the
            updated terms.
          </p>
        </Section>

        <Section title="10. Governing law">
          <p>
            These terms are governed by the laws of the State of Florida,
            United States. Any dispute will be resolved in the state or
            federal courts of Duval County, Florida, except where a
            consumer protection law requires another venue.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Questions:{" "}
            <a href="mailto:hello@regimen.app" className="text-[var(--foreground)] underline underline-offset-2">
              hello@regimen.app
            </a>
            . Security disclosures:{" "}
            <a href="mailto:security@regimen.app" className="text-[var(--foreground)] underline underline-offset-2">
              security@regimen.app
            </a>
            .
          </p>
        </Section>
      </article>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="mb-3 text-title-3 text-[var(--foreground)]">{title}</h2>
      <div className="space-y-4">{children}</div>
    </section>
  );
}
